### ISSUE TITLE
Ping for previous contributors

### ISSUE THREAD

**Issue by zhil** [msgphp2/user-bundle#1]
According to https://web.archive.org/web/20201103085630/https://github.com/msgphp/user-bundle/contributors_list?count=8&current_repository=user-bundle&items_to_show=8 bundle had 8 contributors.

![image](https://github.com/msgphp2/user-bundle/assets/981783/c11cbcf1-db55-488c-9f56-d1ea5fda322c)

@bbuehrle @dreadnip @DevMDamien @abunch @pascalwacker @tacman @GawainLynch @ro0NL
welcome to the new location for the msgphp/user-bundle!

Feel free to use and contribute :)

**Comment by ro0NL** [comment]
i can transfer org also ;)

**Comment by zhil** [comment]
probably, the best solution will be restoring everything under msgphp/* org.

It will simplify package update and also existing links/references will work as is. Also I wasnt able to find repositories with .git history, current msgphp2/* - are just snippets from vendor folder.

@ro0NL so, what do you think about removing msgphp2 and restoring msgphp? :)

**Comment by ro0NL** [comment]
if there's a new owner, then yes

**Comment by ro0NL** [comment]
i've sent you an invite for ownership

**Comment by zhil** [comment]
@ro0NL ok, I joined org.
just wonder - why did you decide to archive all repositories? I send you email in case if you will want to discuss that privately

**Comment by ro0NL** [comment]
i gave up the project :)

i kept the archive for situations like this

**Comment by ro0NL** [comment]
i've deleted myself from org

can you verify everything works for you?

good luck!

**Comment by zhil** [comment]
Yes, everything seems to works fine, thanks.

I dont really have plans to actively contribute to these bundles too, but I still use this bundles for a couple live projects in production and composer are broken without live repositories. Also I recently fixed sonataAdminBundle compatiblity bug, going to push that live

So, I think, that it will be better for everybody, if these bundles will be public - at least composer install will keep working.

@ro0NL thanks for fast response and have a good day!

**Comment by zhil** [comment]
https://github.com/msgphp/ is working fine now.

Anybody interested - feel free to use and contribute
